import type { Kana, Particle } from "@/type";

export const hiraganas: Kana[][] = [
  [
    {
      literal: "あ",
      romaji: "a",
      unicode: "U+3042",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "a",
      gojuonColumn: "a",
    },
    {
      literal: "い",
      romaji: "i",
      unicode: "U+3044",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "a",
      gojuonColumn: "i",
      youon: [{ literal: "いぇ", romaji: "ye" }],
    },
    {
      literal: "う",
      romaji: "u",
      unicode: "U+3046",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "a",
      gojuonColumn: "u",
      youon: [
        { literal: "うぃ", romaji: "wi" },
        { literal: "うぇ", romaji: "we" },
        { literal: "うぉ", romaji: "wo" },
      ],
    },
    {
      literal: "え",
      romaji: "e",
      unicode: "U+3048",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "a",
      gojuonColumn: "e",
    },
    {
      literal: "お",
      romaji: "o",
      unicode: "U+304A",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "a",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "か",
      romaji: "ka",
      unicode: "U+304B",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "ka",
      gojuonColumn: "a",
      dakuten: { literal: "が", romaji: "ga" },
    },
    {
      literal: "き",
      romaji: "ki",
      unicode: "U+304D",
      strokeCount: 4,
      type: "hiragana",
      gojuonRow: "ka",
      gojuonColumn: "i",
      dakuten: { literal: "ぎ", romaji: "gi" },
      youon: [
        { literal: "きゃ", romaji: "kya" },
        { literal: "きゅ", romaji: "kyu" },
        { literal: "きょ", romaji: "kyo" },
      ],
    },
    {
      literal: "く",
      romaji: "ku",
      unicode: "U+304F",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ka",
      gojuonColumn: "u",
      dakuten: { literal: "ぐ", romaji: "gu" },
      youon: [{ literal: "くゎ", romaji: "kwa" }],
    },
    {
      literal: "け",
      romaji: "ke",
      unicode: "U+3051",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "ka",
      gojuonColumn: "e",
      dakuten: { literal: "げ", romaji: "ge" },
    },
    {
      literal: "こ",
      romaji: "ko",
      unicode: "U+3053",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ka",
      gojuonColumn: "o",
      dakuten: { literal: "ご", romaji: "go" },
    },
  ],
  [
    {
      literal: "さ",
      romaji: "sa",
      unicode: "U+3055",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "sa",
      gojuonColumn: "a",
      dakuten: { literal: "ざ", romaji: "za" },
    },
    {
      literal: "し",
      romaji: "shi",
      unicode: "U+3057",
      strokeCount: 1,
      type: "hiragana",
      particle: true,
      gojuonRow: "sa",
      gojuonColumn: "i",
      dakuten: { literal: "じ", romaji: "ji" },
      youon: [
        { literal: "しゃ", romaji: "sha" },
        { literal: "しゅ", romaji: "shu" },
        { literal: "しょ", romaji: "sho" },
      ],
    },
    {
      literal: "す",
      romaji: "su",
      unicode: "U+3059",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "sa",
      gojuonColumn: "u",
      dakuten: { literal: "ず", romaji: "zu" },
      youon: [{ literal: "すぃ", romaji: "si" }],
    },
    {
      literal: "せ",
      romaji: "se",
      unicode: "U+305B",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "sa",
      gojuonColumn: "e",
      dakuten: { literal: "ぜ", romaji: "ze" },
    },
    {
      literal: "そ",
      romaji: "so",
      unicode: "U+305D",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "sa",
      gojuonColumn: "o",
      dakuten: { literal: "ぞ", romaji: "zo" },
    },
  ],
  [
    {
      literal: "た",
      romaji: "ta",
      unicode: "U+305F",
      strokeCount: 4,
      type: "hiragana",
      gojuonRow: "ta",
      gojuonColumn: "a",
      dakuten: { literal: "だ", romaji: "da" },
    },
    {
      literal: "ち",
      romaji: "chi",
      unicode: "U+3061",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ta",
      gojuonColumn: "i",
      dakuten: { literal: "ぢ", romaji: "dji" },
      youon: [
        { literal: "ちゃ", romaji: "cha" },
        { literal: "ちゅ", romaji: "chu" },
        { literal: "ちょ", romaji: "cho" },
      ],
    },
    {
      literal: "つ",
      romaji: "tsu",
      unicode: "U+3064",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ta",
      gojuonColumn: "u",
      dakuten: { literal: "づ", romaji: "dzu" },
      small: "っ",
    },
    {
      literal: "て",
      romaji: "te",
      unicode: "U+3066",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ta",
      gojuonColumn: "e",
      dakuten: { literal: "で", romaji: "de" },
    },
    {
      literal: "と",
      romaji: "to",
      unicode: "U+3068",
      strokeCount: 2,
      type: "hiragana",
      particle: true,
      gojuonRow: "ta",
      gojuonColumn: "o",
      dakuten: { literal: "ど", romaji: "do" },
    },
  ],
  [
    {
      literal: "な",
      romaji: "na",
      unicode: "U+306A",
      strokeCount: 4,
      type: "hiragana",
      gojuonRow: "na",
      gojuonColumn: "a",
    },
    {
      literal: "に",
      romaji: "ni",
      unicode: "U+306B",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "na",
      gojuonColumn: "i",
      youon: [
        { literal: "にゃ", romaji: "nya" },
        { literal: "にゅ", romaji: "nyu" },
        { literal: "にょ", romaji: "nyo" },
      ],
    },
    {
      literal: "ぬ",
      romaji: "nu",
      unicode: "U+306C",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "na",
      gojuonColumn: "u",
    },
    {
      literal: "ね",
      romaji: "ne",
      unicode: "U+306D",
      strokeCount: 2,
      type: "hiragana",
      particle: true,
      gojuonRow: "na",
      gojuonColumn: "e",
    },
    {
      literal: "の",
      romaji: "no",
      unicode: "U+306E",
      strokeCount: 1,
      type: "hiragana",
      particle: true,
      gojuonRow: "na",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "は",
      romaji: "ha",
      unicode: "U+306F",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "ha",
      gojuonColumn: "a",
      dakuten: { literal: "ば", romaji: "ba" },
      handakuten: { literal: "ぱ", romaji: "pa" },
    },
    {
      literal: "ひ",
      romaji: "hi",
      unicode: "U+3072",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ha",
      gojuonColumn: "i",
      dakuten: { literal: "び", romaji: "bi" },
      handakuten: { literal: "ぴ", romaji: "pi" },
      youon: [
        { literal: "ひゃ", romaji: "hya" },
        { literal: "ひゅ", romaji: "hyu" },
        { literal: "ひょ", romaji: "hyo" },
      ],
    },
    {
      literal: "ふ",
      romaji: "fu",
      unicode: "U+3075",
      strokeCount: 4,
      type: "hiragana",
      gojuonRow: "ha",
      gojuonColumn: "u",
      dakuten: { literal: "ぶ", romaji: "bu" },
      handakuten: { literal: "ぷ", romaji: "pu" },
      youon: [
        { literal: "ふぁ", romaji: "fa" },
        { literal: "ふぃ", romaji: "fi" },
        { literal: "ふぇ", romaji: "fe" },
        { literal: "ふぉ", romaji: "fo" },
      ],
    },
    {
      literal: "へ",
      romaji: "he",
      unicode: "U+3078",
      strokeCount: 1,
      type: "hiragana",
      particle: true,
      gojuonRow: "ha",
      gojuonColumn: "e",
      dakuten: { literal: "べ", romaji: "be" },
      handakuten: { literal: "ぺ", romaji: "pe" },
    },
    {
      literal: "ほ",
      romaji: "ho",
      unicode: "U+307B",
      strokeCount: 4,
      type: "hiragana",
      gojuonRow: "ha",
      gojuonColumn: "o",
      dakuten: { literal: "ぼ", romaji: "bo" },
      handakuten: { literal: "ぽ", romaji: "po" },
    },
  ],
  [
    {
      literal: "ま",
      romaji: "ma",
      unicode: "U+307E",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "ma",
      gojuonColumn: "a",
    },
    {
      literal: "み",
      romaji: "mi",
      unicode: "U+307F",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ma",
      gojuonColumn: "i",
      youon: [
        { literal: "みゃ", romaji: "mya" },
        { literal: "みゅ", romaji: "myu" },
        { literal: "みょ", romaji: "myo" },
      ],
    },
    {
      literal: "む",
      romaji: "mu",
      unicode: "U+3080",
      strokeCount: 3,
      type: "hiragana",
      gojuonRow: "ma",
      gojuonColumn: "u",
    },
    {
      literal: "め",
      romaji: "me",
      unicode: "U+3081",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ma",
      gojuonColumn: "e",
    },
    {
      literal: "も",
      romaji: "mo",
      unicode: "U+3082",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "ma",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "や",
      romaji: "ya",
      unicode: "U+3084",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "ya",
      gojuonColumn: "a",
      small: "ゃ",
    },
    {
      literal: "ゆ",
      romaji: "yu",
      unicode: "U+3086",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ya",
      gojuonColumn: "u",
      small: "ゅ",
    },
    {
      literal: "よ",
      romaji: "yo",
      unicode: "U+3088",
      strokeCount: 2,
      type: "hiragana",
      particle: true,
      gojuonRow: "ya",
      gojuonColumn: "o",
      small: "ょ",
    },
  ],
  [
    {
      literal: "ら",
      romaji: "ra",
      unicode: "U+3089",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ra",
      gojuonColumn: "a",
    },
    {
      literal: "り",
      romaji: "ri",
      unicode: "U+308A",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ra",
      gojuonColumn: "i",
      youon: [
        { literal: "りゃ", romaji: "rya" },
        { literal: "りゅ", romaji: "ryu" },
        { literal: "りょ", romaji: "ryo" },
      ],
    },
    {
      literal: "る",
      romaji: "ru",
      unicode: "U+308B",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ra",
      gojuonColumn: "u",
    },
    {
      literal: "れ",
      romaji: "re",
      unicode: "U+308C",
      strokeCount: 2,
      type: "hiragana",
      gojuonRow: "ra",
      gojuonColumn: "e",
    },
    {
      literal: "ろ",
      romaji: "ro",
      unicode: "U+308D",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "ra",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "わ",
      romaji: "wa",
      unicode: "U+308F",
      strokeCount: 2,
      type: "hiragana",
      particle: true,
      gojuonRow: "wa",
      gojuonColumn: "a",
      small: "ゎ",
    },
    {
      literal: "を",
      romaji: "wo",
      unicode: "U+3092",
      strokeCount: 3,
      type: "hiragana",
      particle: true,
      gojuonRow: "wa",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "ん",
      romaji: "n",
      unicode: "U+3093",
      strokeCount: 1,
      type: "hiragana",
      gojuonRow: "n",
      gojuonColumn: "n",
    },
  ],
];

export const katakanas: Kana[][] = [
  [
    {
      literal: "ア",
      romaji: "a",
      unicode: "U+30A2",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "a",
      gojuonColumn: "a",
      small: "ァ",
    },
    {
      literal: "イ",
      romaji: "i",
      unicode: "U+30A4",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "a",
      gojuonColumn: "i",
      small: "ィ",
      youon: [{ literal: "イェ", romaji: "ye" }],
    },
    {
      literal: "ウ",
      romaji: "u",
      unicode: "U+30A6",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "a",
      gojuonColumn: "u",
      small: "ゥ",
      dakuten: { literal: "ヴ", romaji: "vu" },
      youon: [
        { literal: "ウィ", romaji: "wi" },
        { literal: "ウェ", romaji: "we" },
        { literal: "ウォ", romaji: "wo" },
      ],
    },
    {
      literal: "エ",
      romaji: "e",
      unicode: "U+30A8",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "a",
      gojuonColumn: "e",
      small: "ェ",
    },
    {
      literal: "オ",
      romaji: "o",
      unicode: "U+30AA",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "a",
      gojuonColumn: "o",
      small: "ォ",
    },
  ],
  [
    {
      literal: "カ",
      romaji: "ka",
      unicode: "U+30AB",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ka",
      gojuonColumn: "a",
      dakuten: { literal: "ガ", romaji: "ga" },
      small: "ヵ",
    },
    {
      literal: "キ",
      romaji: "ki",
      unicode: "U+30AD",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ka",
      gojuonColumn: "i",
      dakuten: { literal: "ギ", romaji: "gi" },
      youon: [
        { literal: "キャ", romaji: "kya" },
        { literal: "キュ", romaji: "kyu" },
        { literal: "キョ", romaji: "kyo" },
      ],
    },
    {
      literal: "ク",
      romaji: "ku",
      unicode: "U+30AF",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ka",
      gojuonColumn: "u",
      dakuten: { literal: "グ", romaji: "gu" },
      youon: [
        { literal: "クァ", romaji: "kwa" },
        { literal: "クィ", romaji: "kwi" },
        { literal: "クェ", romaji: "kwe" },
        { literal: "クォ", romaji: "kwo" },
      ],
    },
    {
      literal: "ケ",
      romaji: "ke",
      unicode: "U+30B1",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ka",
      gojuonColumn: "e",
      dakuten: { literal: "ゲ", romaji: "ge" },
      small: "ヶ",
    },
    {
      literal: "コ",
      romaji: "ko",
      unicode: "U+30B3",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ka",
      gojuonColumn: "o",
      dakuten: { literal: "ゴ", romaji: "go" },
    },
  ],
  [
    {
      literal: "サ",
      romaji: "sa",
      unicode: "U+30B5",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "sa",
      gojuonColumn: "a",
      dakuten: { literal: "ザ", romaji: "za" },
    },
    {
      literal: "シ",
      romaji: "shi",
      unicode: "U+30B7",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "sa",
      gojuonColumn: "i",
      dakuten: { literal: "ジ", romaji: "ji" },
      youon: [
        { literal: "シャ", romaji: "sha" },
        { literal: "シュ", romaji: "shu" },
        { literal: "シェ", romaji: "she" },
        { literal: "ショ", romaji: "sho" },
      ],
    },
    {
      literal: "ス",
      romaji: "su",
      unicode: "U+30B9",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "sa",
      gojuonColumn: "u",
      dakuten: { literal: "ズ", romaji: "zu" },
      youon: [{ literal: "スィ", romaji: "si" }],
    },
    {
      literal: "セ",
      romaji: "se",
      unicode: "U+30BB",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "sa",
      gojuonColumn: "e",
      dakuten: { literal: "ゼ", romaji: "ze" },
    },
    {
      literal: "ソ",
      romaji: "so",
      unicode: "U+30BD",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "sa",
      gojuonColumn: "o",
      dakuten: { literal: "ゾ", romaji: "zo" },
    },
  ],
  [
    {
      literal: "タ",
      romaji: "ta",
      unicode: "U+30BF",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ta",
      gojuonColumn: "a",
      dakuten: { literal: "ダ", romaji: "da" },
    },
    {
      literal: "チ",
      romaji: "chi",
      unicode: "U+30C1",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ta",
      gojuonColumn: "i",
      dakuten: { literal: "ヂ", romaji: "dji" },
      youon: [
        { literal: "チャ", romaji: "cha" },
        { literal: "チュ", romaji: "chu" },
        { literal: "チェ", romaji: "che" },
        { literal: "チョ", romaji: "cho" },
      ],
    },
    {
      literal: "ツ",
      romaji: "tsu",
      unicode: "U+30C4",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ta",
      gojuonColumn: "u",
      dakuten: { literal: "ヅ", romaji: "dzu" },
      small: "ッ",
      youon: [
        { literal: "ツァ", romaji: "tsa" },
        { literal: "ツィ", romaji: "tsi" },
        { literal: "ツェ", romaji: "tse" },
        { literal: "ツォ", romaji: "tso" },
      ],
    },
    {
      literal: "テ",
      romaji: "te",
      unicode: "U+30C6",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ta",
      gojuonColumn: "e",
      dakuten: { literal: "デ", romaji: "de" },
      youon: [
        { literal: "テャ", romaji: "tya" },
        { literal: "テュ", romaji: "tyu" },
        { literal: "テョ", romaji: "tyo" },
      ],
    },
    {
      literal: "ト",
      romaji: "to",
      unicode: "U+30C8",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ta",
      gojuonColumn: "o",
      dakuten: { literal: "ド", romaji: "do" },
      youon: [{ literal: "トゥ", romaji: "tu" }],
    },
  ],
  [
    {
      literal: "ナ",
      romaji: "na",
      unicode: "U+30CA",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "na",
      gojuonColumn: "a",
    },
    {
      literal: "ニ",
      romaji: "ni",
      unicode: "U+30CB",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "na",
      gojuonColumn: "i",
      youon: [
        { literal: "ニャ", romaji: "nya" },
        { literal: "ニュ", romaji: "nyu" },
        { literal: "ニョ", romaji: "nyo" },
      ],
    },
    {
      literal: "ヌ",
      romaji: "nu",
      unicode: "U+30CC",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "na",
      gojuonColumn: "u",
    },
    {
      literal: "ネ",
      romaji: "ne",
      unicode: "U+30CD",
      strokeCount: 4,
      type: "katakana",
      gojuonRow: "na",
      gojuonColumn: "e",
    },
    {
      literal: "ノ",
      romaji: "no",
      unicode: "U+30CE",
      strokeCount: 1,
      type: "katakana",
      gojuonRow: "na",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "ハ",
      romaji: "ha",
      unicode: "U+30CF",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ha",
      gojuonColumn: "a",
      dakuten: { literal: "バ", romaji: "ba" },
      handakuten: { literal: "パ", romaji: "pa" },
    },
    {
      literal: "ヒ",
      romaji: "hi",
      unicode: "U+30D2",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ha",
      gojuonColumn: "i",
      dakuten: { literal: "ビ", romaji: "bi" },
      handakuten: { literal: "ピ", romaji: "pi" },
      youon: [
        { literal: "ヒャ", romaji: "hya" },
        { literal: "ヒュ", romaji: "hyu" },
        { literal: "ヒョ", romaji: "hyo" },
      ],
    },
    {
      literal: "フ",
      romaji: "fu",
      unicode: "U+30D5",
      strokeCount: 1,
      type: "katakana",
      gojuonRow: "ha",
      gojuonColumn: "u",
      dakuten: { literal: "ブ", romaji: "bu" },
      handakuten: { literal: "プ", romaji: "pu" },
      youon: [
        { literal: "ファ", romaji: "fa" },
        { literal: "フィ", romaji: "fi" },
        { literal: "フェ", romaji: "fe" },
        { literal: "フォ", romaji: "fo" },
        { literal: "フュ", romaji: "fyu" },
      ],
    },
    {
      literal: "ヘ",
      romaji: "he",
      unicode: "U+30D8",
      strokeCount: 1,
      type: "katakana",
      gojuonRow: "ha",
      gojuonColumn: "e",
      dakuten: { literal: "ベ", romaji: "be" },
      handakuten: { literal: "ペ", romaji: "pe" },
    },
    {
      literal: "ホ",
      romaji: "ho",
      unicode: "U+30DB",
      strokeCount: 4,
      type: "katakana",
      gojuonRow: "ha",
      gojuonColumn: "o",
      dakuten: { literal: "ボ", romaji: "bo" },
      handakuten: { literal: "ポ", romaji: "po" },
    },
  ],
  [
    {
      literal: "マ",
      romaji: "ma",
      unicode: "U+30DE",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ma",
      gojuonColumn: "a",
    },
    {
      literal: "ミ",
      romaji: "mi",
      unicode: "U+30DF",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ma",
      gojuonColumn: "i",
      youon: [
        { literal: "ミャ", romaji: "mya" },
        { literal: "ミュ", romaji: "myu" },
        { literal: "ミョ", romaji: "myo" },
      ],
    },
    {
      literal: "ム",
      romaji: "mu",
      unicode: "U+30E0",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ma",
      gojuonColumn: "u",
    },
    {
      literal: "メ",
      romaji: "me",
      unicode: "U+30E1",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ma",
      gojuonColumn: "e",
    },
    {
      literal: "モ",
      romaji: "mo",
      unicode: "U+30E2",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ma",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "ヤ",
      romaji: "ya",
      unicode: "U+30E4",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ya",
      gojuonColumn: "a",
      small: "ャ",
    },
    {
      literal: "ユ",
      romaji: "yu",
      unicode: "U+30E6",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ya",
      gojuonColumn: "u",
      small: "ュ",
    },
    {
      literal: "ヨ",
      romaji: "yo",
      unicode: "U+30E8",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ya",
      gojuonColumn: "o",
      small: "ョ",
    },
  ],
  [
    {
      literal: "ラ",
      romaji: "ra",
      unicode: "U+30E9",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ra",
      gojuonColumn: "a",
    },
    {
      literal: "リ",
      romaji: "ri",
      unicode: "U+30EA",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ra",
      gojuonColumn: "i",
      youon: [
        { literal: "リャ", romaji: "rya" },
        { literal: "リュ", romaji: "ryu" },
        { literal: "リョ", romaji: "ryo" },
      ],
    },
    {
      literal: "ル",
      romaji: "ru",
      unicode: "U+30EB",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "ra",
      gojuonColumn: "u",
    },
    {
      literal: "レ",
      romaji: "re",
      unicode: "U+30EC",
      strokeCount: 1,
      type: "katakana",
      gojuonRow: "ra",
      gojuonColumn: "e",
    },
    {
      literal: "ロ",
      romaji: "ro",
      unicode: "U+30ED",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "ra",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "ワ",
      romaji: "wa",
      unicode: "U+30EF",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "wa",
      gojuonColumn: "a",
      small: "ヮ",
    },
    {
      literal: "ヲ",
      romaji: "wo",
      unicode: "U+30F2",
      strokeCount: 3,
      type: "katakana",
      gojuonRow: "wa",
      gojuonColumn: "o",
    },
  ],
  [
    {
      literal: "ン",
      romaji: "n",
      unicode: "U+30F3",
      strokeCount: 2,
      type: "katakana",
      gojuonRow: "n",
      gojuonColumn: "n",
    },
  ],
];

export const particles: Particle[] = [
  {
    literal: "は",
    romaji: "wa",
    use: 'Topic marker - marks the topic of a sentence (pronounced "wa" as particle, not "ha")',
  },
  {
    literal: "が",
    romaji: "ga",
    use: "Subject marker - marks the grammatical subject of a sentence",
  },
  {
    literal: "を",
    romaji: "o",
    use: 'Direct object marker - marks the direct object of an action (pronounced "o" as particle, not "wo")',
  },
  {
    literal: "に",
    romaji: "ni",
    use: "Direction/location/time marker - indicates direction, destination, location of existence, or time",
  },
  {
    literal: "へ",
    romaji: "e",
    use: 'Direction marker - indicates direction or destination (pronounced "e" as particle, not "he")',
  },
  {
    literal: "で",
    romaji: "de",
    use: "Location/means marker - indicates location of action or means/method by which something is done",
  },
  {
    literal: "と",
    romaji: "to",
    use: 'Conjunction - means "and" (for complete lists) or "with" (accompaniment)',
  },
  {
    literal: "や",
    romaji: "ya",
    use: 'Conjunction - means "and" for non-exhaustive lists (implies there are other items)',
  },
  {
    literal: "か",
    romaji: "ka",
    use: "Question marker - placed at the end of a sentence to form a question",
  },
  {
    literal: "の",
    romaji: "no",
    use: "Possessive/descriptive marker - shows possession or connects nouns descriptively",
  },
  {
    literal: "も",
    romaji: "mo",
    use: 'Inclusive marker - means "also" or "too", replaces は/が/を',
  },
  {
    literal: "から",
    romaji: "kara",
    use: 'Source/reason marker - means "from" (source/starting point) or "because" (reason)',
  },
  {
    literal: "まで",
    romaji: "made",
    use: 'Limit marker - means "until" or "up to" (ending point in time or space)',
  },
  {
    literal: "より",
    romaji: "yori",
    use: 'Comparison/source marker - means "than" (in comparisons) or "from" (formal)',
  },
  {
    literal: "ね",
    romaji: "ne",
    use: 'Sentence-ending particle - seeks confirmation or agreement, like "right?" or "isn\'t it?"',
  },
  {
    literal: "よ",
    romaji: "yo",
    use: "Sentence-ending particle - adds emphasis or provides new information to the listener",
  },
  {
    literal: "よね",
    romaji: "yone",
    use: "Sentence-ending particle - combination of よ and ね, seeks confirmation with emphasis",
  },
  {
    literal: "ぞ",
    romaji: "zo",
    use: "Sentence-ending particle - masculine, adds strong emphasis or assertion",
  },
  {
    literal: "ぜ",
    romaji: "ze",
    use: "Sentence-ending particle - masculine, casual emphasis (softer than ぞ)",
  },
  {
    literal: "わ",
    romaji: "wa",
    use: "Sentence-ending particle - traditionally feminine, adds gentle emphasis",
  },
  {
    literal: "な",
    romaji: "na",
    use: "Sentence-ending particle - masculine prohibition (don't!) or emotional exclamation",
  },
  {
    literal: "なあ",
    romaji: "naa",
    use: "Sentence-ending particle - expresses emotion, reflection, or seeking agreement",
  },
  {
    literal: "さ",
    romaji: "sa",
    use: "Sentence-ending particle - casual filler, light emphasis",
  },
  {
    literal: "の",
    romaji: "no",
    use: "Sentence-ending particle - casual explanation or feminine emphasis (different from possessive の)",
  },
  {
    literal: "のね",
    romaji: "none",
    use: "Sentence-ending particle - explanatory with confirmation seeking",
  },
  {
    literal: "って",
    romaji: "tte",
    use: "Quotation/topic marker - casual quotation or introduces topics (casual form of と)",
  },
  {
    literal: "し",
    romaji: "shi",
    use: 'Conjunction - lists reasons or adds information, means "and what\'s more"',
  },
  {
    literal: "けど",
    romaji: "kedo",
    use: 'Conjunction - means "but" or "however" (casual)',
  },
  {
    literal: "が",
    romaji: "ga",
    use: 'Conjunction - means "but" or "however" (when connecting clauses, different from subject marker)',
  },
  {
    literal: "ても",
    romaji: "temo",
    use: 'Conjunction - means "even if" or "even though"',
  },
  {
    literal: "たり",
    romaji: "tari",
    use: "Conjunction - lists actions or states as examples among others",
  },
  {
    literal: "ながら",
    romaji: "nagara",
    use: 'Conjunction - means "while" (doing two actions simultaneously)',
  },
  {
    literal: "のに",
    romaji: "noni",
    use: 'Conjunction - means "despite" or "although" (expresses contradiction)',
  },
  {
    literal: "ば",
    romaji: "ba",
    use: 'Conditional - means "if" (conditional form)',
  },
  {
    literal: "たら",
    romaji: "tara",
    use: 'Conditional - means "if/when" (conditional or temporal)',
  },
  {
    literal: "なら",
    romaji: "nara",
    use: 'Conditional - means "if" (contextual or hypothetical condition)',
  },
  {
    literal: "ところ",
    romaji: "tokoro",
    use: "Temporal marker - indicates timing or current state of action",
  },
  {
    literal: "ほど",
    romaji: "hodo",
    use: 'Extent marker - indicates degree or extent, "as...as" or "to the extent that"',
  },
  {
    literal: "ずつ",
    romaji: "zutsu",
    use: 'Distribution marker - means "each" or "at a time" (equal distribution)',
  },
  {
    literal: "だけ",
    romaji: "dake",
    use: 'Limitation marker - means "only" or "just"',
  },
  {
    literal: "しか",
    romaji: "shika",
    use: 'Limitation marker - means "only" (used with negative, emphasizes limitation)',
  },
  {
    literal: "ばかり",
    romaji: "bakari",
    use: 'Approximation/exclusivity marker - means "just/only" or "about/approximately"',
  },
  {
    literal: "くらい",
    romaji: "kurai",
    use: 'Approximation marker - means "about/approximately" or "to the extent of"',
  },
  {
    literal: "ぐらい",
    romaji: "gurai",
    use: "Approximation marker - same as くらい (alternate pronunciation)",
  },
  {
    literal: "など",
    romaji: "nado",
    use: 'Exemplification marker - means "and so on", "etc.", or "such as"',
  },
  {
    literal: "なんか",
    romaji: "nanka",
    use: 'Exemplification/dismissive marker - casual "things like" or dismissive nuance',
  },
  {
    literal: "なんて",
    romaji: "nante",
    use: "Exemplification/quotation marker - casual quotation or expresses surprise/disdain",
  },
  {
    literal: "こそ",
    romaji: "koso",
    use: 'Emphasis marker - emphasizes the preceding word, "precisely" or "exactly"',
  },
  {
    literal: "さえ",
    romaji: "sae",
    use: 'Extreme marker - means "even" (emphasizes extremity)',
  },
  {
    literal: "でも",
    romaji: "demo",
    use: 'Conjunction/exemplification - means "but" or "or something" (suggests alternatives)',
  },
  {
    literal: "っけ",
    romaji: "kke",
    use: 'Sentence-ending particle - recalls information, "wasn\'t it?" or "I wonder"',
  },
  {
    literal: "かい",
    romaji: "kai",
    use: "Question marker - masculine casual question particle",
  },
  {
    literal: "かしら",
    romaji: "kashira",
    use: 'Question marker - feminine wondering, "I wonder"',
  },
];
